### ISSUE TITLE
:optimizations :none ---> omg it happened null nil

### ISSUE THREAD

**Issue by raoofha** [anmonteiro/lumo#229] opened 2017-08-06 04:25 UTC
hi
lumo can not compile with optimizations set to none 
```
omg it happened null nil
failed compiling file:out/cljs/core.cljs
         (new)
         Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1935:200)
         (evalmachine.<anonymous>:609:25)
         Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
         (Object.lumo$closure$compile_file)
         lumo.closure._compile.string (evalmachine.<anonymous>:1582:21)
         (Object.lumo$closure$_compile)
         (Object.lumo$closure$compile_from_jar)
         lumo.closure._compile.object (evalmachine.<anonymous>:1607:21)
         (Object.lumo$closure$_compile)

should never happen!
         (new)
         Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1935:200)
         Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:1935:88)
         (Object.lumo$io$slurp)
         (Object.lumo$compiler$emit_cached_core)
         (evalmachine.<anonymous>:482:28)
         Function.lumo.compiler.with_core_cljs.cljs$core$IFn$_invoke$arity$2 (evalmachine.<anonymous>:231:85)
         Function.lumo.compiler.compile_file_STAR_.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:461:41)
         (evalmachine.<anonymous>:586:41)
         Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
```

**Comment by anmonteiro** [comment] 2017-08-06 04:27
Can you put together a repro? There's absolutely no information in this issue.

**Comment by anmonteiro** [comment] 2017-08-06 04:37
duplicate of #132 . `:source-map false` makes compilation succeed

**Comment by raoofha** [comment] 2017-08-06 04:38
sorry
I just have a file at src/lumo_test/core.cljs
```
(ns lumo-test.core)

(print "hello world")
```
and build.cljs
```
(require '[lumo.build.api :as b])
(b/build "src"
  {:main 'lumo-test.core
   :output-to "main.js"
   :optimizations :none
   })
```
and when executing ```lumo -c src build.cljs``` it gave me the error

**Closed by anmonteiro** 2017-08-06 04:37 UTC

**Comment by chrisdavies** [comment] 2017-08-14 18:08
I got this just today. I simply left the `:optimizations` option out altogether.
