### ISSUE TITLE
Compiling code with Maven dependencies

### ISSUE THREAD

**Issue by moea** [anmonteiro/lumo#239] opened 2017-08-24 14:27 UTC
Apologies if this is a naive question, I'm not familiar with the details of the project.

If I require a namespace provided by a Maven dependency listed in `-D`, it works as expected.  If I _compile_ code (i.e. using the build API) which requires that same namespace within a process started with the same options, I get an error.  How should I go about providing dependencies in a case like this?

I picked andare, to experiment  - when compiling code which requires `cljs.core.async`, I get:

`Could not analyze dep cljs.core.async.impl.protocols`, among other errors, which is obviously different from the errors I get if I don't pass in the dependency at all.

**Comment by anmonteiro** [comment] 2017-08-24 16:36
This might be a problem with compilation itself.

**Comment by arichiardi** [comment] 2017-08-29 21:49
I have the same problem with local dependencies it seems. So for instance if I compile:

```
(ns my.test-namespace
  (:require [cljs.pprint :as pprint]))
```

everything is ok, but if I have something like:

```
(ns my.test-namespace
  (:require [my.test-util]))
```

and

```
(ns my.test-util
  (:require [cljs.pprint :as pprint]))
```

then compilation fails...can it be related to requiring?

**Comment by arichiardi** [comment] 2017-08-29 21:55
The error that it gives me is [in this gist](https://gist.github.com/arichiardi/f93e67aa43ca0846615899baa61742b5)

**Comment by arichiardi** [comment] 2017-09-03 23:46
So it seems that the `-D` option does not fetch dependencies:

```console
$ lumo -D andare:0.7.0
Lumo 1.7.0
ClojureScript 1.9.908
Node.js v8.4.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (require '[cljs.core.async :as async :refer [<! >!]])
nil
cljs.user=> 
```

```console
$ rm -Rf ~/.m2/repository/andare/andare/0.7.0/
$ lumo -D andare:0.7.0
Lumo 1.7.0
ClojureScript 1.9.908
Node.js v8.4.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (require '[cljs.core.async :as async :refer [<! >!]])
No such namespace: cljs.core.async, could not locate cljs/core/async.cljs, cljs/core/async.cljc, or JavaScript source providing "cljs.core.async"
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2555:92)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:2554:92)
	 (NO_SOURCE_FILE <embedded>:5553:162)
	 Object.lumo.repl.load_other (NO_SOURCE_FILE <embedded>:6351:378)
	 lumo.repl.load (NO_SOURCE_FILE <embedded>:6355:96)
	 Function.cljs.js.require.cljs$core$IFn$_invoke$arity$5 (NO_SOURCE_FILE <embedded>:5555:77)
	 Function.cljs.js.load_deps.cljs$core$IFn$_invoke$arity$7 (NO_SOURCE_FILE <embedded>:5565:231)
	 Function.cljs.js.ns_side_effects.cljs$core$IFn$_invoke$arity$6 (NO_SOURCE_FILE <embedded>:5619:287)

cljs.user=> 
```

**Comment by moea** [comment] 2017-09-04 11:54
That behaviour is not related to the issue I was reporting.

**Comment by arichiardi** [comment] 2017-09-05 17:16
I don't see any compilation error by requiring `cljs.core.async` though here, would you mind sharing a piece of code, maybe I am not testing the same code path.

**Comment by arichiardi** [comment] 2017-09-05 17:42
Ok I have been able to reproduce it, maybe it is connected to #243.

It seems like the most important details of the stack trace are:

```
Invoking the Lumo compiler w/ inputs ["src"]
Copying jar:file:!/cljs/core.cljs to out/cljs/core.cljs
Compiling out/cljs/core.cljs
Using cached cljs.core out/cljs/core.cljs
Copying jar:file:!/cljs/pprint.cljs to out/cljs/pprint.cljs
Compiling out/cljs/pprint.cljs
Compiling src/cqrs_cloud/util.cljs
Copying jar:file:/home/arichiardi/.m2/repository/org/clojure/core.async/0.3.443/core.async-0.3.443.jar!/cljs/core/async/impl/protocols.cljs to out/cljs/core/async/impl/protocols.cljs
Compiling out/cljs/core/async/impl/protocols.cljs
Copying jar:file:/home/arichiardi/.m2/repository/org/clojure/core.async/0.3.443/core.async-0.3.443.jar!/cljs/core/async/impl/buffers.cljs to out/cljs/core/async/impl/buffers.cljs
Compiling out/cljs/core/async/impl/buffers.cljs
failed compiling file:out/cljs/core.cljs
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 (evalmachine.<anonymous>:609:25)
	 Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
	 (Object.lumo$closure$compile_file)
	 (evalmachine.<anonymous>:1625:21)
	 (Object.lumo$closure$_compile)
	 (Object.lumo$closure$compile_from_jar)
	 (evalmachine.<anonymous>:1660:21)
	 (Object.lumo$closure$_compile)

failed compiling file:out/cljs/pprint.cljs
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 (evalmachine.<anonymous>:609:25)
	 Function.lumo.compiler.compile_file.cljs$core$IFn$_invoke$arity$4 (evalmachine.<anonymous>:616:4)
	 (Object.lumo$closure$compile_file)
	 (evalmachine.<anonymous>:1625:21)
	 (Object.lumo$closure$_compile)
	 (Object.lumo$closure$compile_from_jar)
	 (evalmachine.<anonymous>:1660:21)
	 (Object.lumo$closure$_compile)

Could not analyze dep cljs.core
```

Note that the compilation of `out/cljs`pprint.cljs` looks successful on the top of the trace, but then it happens again and failes. The thing is, as soon as I don't require `cljs.core.async`, the error goes away. So it is not actually related with `cljs.pprint`.

At the end of the trace I also see:

```
Could not analyze  in file cljs/core/async/impl/protocols.cljs
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2555:92)
	 (NO_SOURCE_FILE <embedded>:5642:383)
	 r (NO_SOURCE_FILE <embedded>:5642:499)
	 (NO_SOURCE_FILE <embedded>:5645:6)
	 (NO_SOURCE_FILE <embedded>:5615:190)
	 Object.cljs.js.load_macros (NO_SOURCE_FILE <embedded>:5588:384)
	 (NO_SOURCE_FILE <embedded>:5609:433)
	 Object.cljs.js.load_macros (NO_SOURCE_FILE <embedded>:5588:384)

Can't redefine a constant at line 11 cljs/core/async/impl/protocols.cljs
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2555:92)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:2554:92)
	 (NO_SOURCE_FILE <embedded>:2750:496)
	 cljs.core.MultiFn.cljs$core$IFn$_invoke$arity$5 (NO_SOURCE_FILE <embedded>:1872:420)
	 Object.cljs.analyzer.analyze_seq_STAR_ (NO_SOURCE_FILE <embedded>:3136:182)
	 Object.cljs.analyzer.analyze_seq_STAR__wrap (NO_SOURCE_FILE <embedded>:3137:83)
	 Function.cljs.analyzer.analyze_seq.cljs$core$IFn$_invoke$arity$4 (NO_SOURCE_FILE <embedded>:3142:81)
	 Object.cljs.analyzer.analyze_form (NO_SOURCE_FILE <embedded>:3179:213)
```

Which might be what triggers the error. Side note, everything works fine at the REPL (not compiling, but requiring).

**Comment by arichiardi** [comment] 2017-09-05 17:59
Promesa exibits the same problem, it seems like it compiles correctly the first time, then not the second time around, because of a constant redef:

```
Using cached cljs.core out/cljs/core.cljs
Copying jar:file:/home/arichiardi/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/protocols.cljc to out/promesa/protocols.cljc
Compiling out/promesa/protocols.cljc
Copying jar:file:/home/arichiardi/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/impl/scheduler.cljc to out/promesa/impl/scheduler.cljc
Compiling out/promesa/impl/scheduler.cljc
Copying jar:file:/home/arichiardi/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/impl.cljc to out/promesa/impl.cljc
Compiling out/promesa/impl.cljc
Copying jar:file:/home/arichiardi/.m2/repository/funcool/promesa/1.9.0/promesa-1.9.0.jar!/promesa/core.cljc to out/promesa/core.cljc

...

Can't redefine a constant at line 47 promesa/impl.cljc
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1923:72)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2555:92)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:2554:92)
	 (NO_SOURCE_FILE <embedded>:2750:496)
	 cljs.core.MultiFn.cljs$core$IFn$_invoke$arity$5 (NO_SOURCE_FILE <embedded>:1872:420)
	 Object.cljs.analyzer.analyze_seq_STAR_ (NO_SOURCE_FILE <embedded>:3136:182)
	 Object.cljs.analyzer.analyze_seq_STAR__wrap (NO_SOURCE_FILE <embedded>:3137:83)
	 Function.cljs.analyzer.analyze_seq.cljs$core$IFn$_invoke$arity$4 (NO_SOURCE_FILE <embedded>:3142:81)
	 Object.cljs.analyzer.analyze_form (NO_SOURCE_FILE <embedded>:3179:213)
```

**Comment by arichiardi** [comment] 2017-09-05 19:31
Trying with the `compiler-tweaks` branch gives out a similar thing:

```
Copying jar:file:!/cljs/core.cljs to out/cljs/core.cljs
Compiling out/cljs/core.cljs
Using cached cljs.core out/cljs/core.cljs
Copying jar:file:!/cljs/pprint.cljs to out/cljs/pprint.cljs
Compiling out/cljs/pprint.cljs
Compiling src/cqrs_cloud/util.cljs
Copying jar:file:/home/arichiardi/.m2/repository/andare/andare/0.7.0/andare-0.7.0.jar!/cljs/core/async/impl/protocols.cljs to out/cljs/core/async/impl/protocols.cljs
Compiling out/cljs/core/async/impl/protocols.cljs
Copying jar:file:/home/arichiardi/.m2/repository/andare/andare/0.7.0/andare-0.7.0.jar!/cljs/core/async/impl/buffers.cljs to out/cljs/core/async/impl/buffers.cljs
Compiling out/cljs/core/async/impl/buffers.cljs
crlh  {:error #error {:message Could not analyze  in file cljs/core/async/impl/protocols.cljs, :data {:tag :cljs/analysis-error}, :cause #error {:message Can't redefine a constant at line 11 cljs/core/async/impl/protocols.cljs, :data {:file cljs/core/async/impl/protocols.cljs, :line 11, :column 1, :tag :cljs/analysis-error}}}}
Copying jar:file:/home/arichiardi/.m2/repository/andare/andare/0.7.0/andare-0.7.0.jar!/cljs/core/async/impl/dispatch.cljs to out/cljs/core/async/impl/dispatch.cljs
Compiling out/cljs/core/async/impl/dispatch.cljs
crlh  {:error #error {:message Could not analyze  in file cljs/core/async/impl/protocols.cljs, :data {:tag :cljs/analysis-error}, :cause #error {:message Can't redefine a constant at line 11 cljs/core/async/impl/protocols.cljs, :data {:file cljs/core/async/impl/protocols.cljs, :line 11, :column 1, :tag :cljs/analysis-error}}}}
```

**Comment by arichiardi** [comment] 2017-09-06 19:48
So from Slack, the reason I found is that:
> so `compile-str` is compiling a namespace...that namespace required an already compiled namespace...that triggers the error for `^:const`

I enabled some more tracing in `compile-tweaks2`, just for me (and whoever is interested), to have a look.

**Comment by arichiardi** [comment] 2017-09-07 19:33
So I tried to add a `*load-fn*` to `lumo.compiler/emit-source`, just for fun:

```clojure
(defn- load [{:keys [name macros path file] :as m} cb]
  (util/debug-prn "--- " m)
  (cond
    (and macros file)
    (cb {:source (io/slurp file)
         :lang :clj
         :file file})

    :else (cb nil)))
```

Now, the output when I try to require `core.async` is:

```console
Compiling out/cljs/core/async/impl/ioc_helpers.cljs
---  {:name cljs.core.async.impl.ioc-macros, :macros true, :path cljs/core/async/impl/ioc_macros}
```

So that's definitely the right path.

*Note*: probably the name of this issue should be now "Cannot compile dependencies the require macros"

**Comment by anmonteiro** [comment] 2017-09-07 23:08
fixed in master

**Closed by anmonteiro** 2017-09-07 23:08 UTC
