### ISSUE TITLE
Dependencies in script mode

### ISSUE THREAD

**Issue by craigy** [anmonteiro/lumo#291] opened 2017-10-05 14:05 UTC
Using lumo 1.8.0-beta

```
$ lumo --version
1.8.0-beta
```

I have a utility script that I've been executing directly with the shebang functionality. However, I want to start using [tools.cli](https://github.com/clojure/tools.cli) to parse script parameters. I tried just adding the `:require` but of course it doesn't work:

```
#!/usr/bin/env lumo
(ns my.script
  (:require
    [clojure.tools.cli :refer [parse-opts]]))

(println "hello world")
```

Now when I try to run the script I get

```
$ ./script.cljs 
No such namespace: cljs.tools.cli, could not locate cljs/tools/cli.cljs, cljs/tools/cli.cljc, or Closure namespace "cljs.tools.cli"
	 (new)
	 Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:1937:200)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 (NO_SOURCE_FILE <embedded>:2484:92)
	 Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$2 (NO_SOURCE_FILE <embedded>:2483:92)
	 (NO_SOURCE_FILE <embedded>:5239:92)
	 Object.lumo.repl.load_other (NO_SOURCE_FILE <embedded>:6123:380)
	 lumo.repl.load (NO_SOURCE_FILE <embedded>:6127:106)
	 Function.cljs.js.require.cljs$core$IFn$_invoke$arity$5 (NO_SOURCE_FILE <embedded>:5229:528)
	 Function.cljs.js.require.cljs$core$IFn$_invoke$arity$4 (NO_SOURCE_FILE <embedded>:5223:88)
	 (NO_SOURCE_FILE <embedded>:5252:423)
```

I know I can run the script using

```
$ lumo -D org.clojure/tools.cli:0.3.5 script.cljs
hello world
```

Is it possible to get this working in script mode? Like a default `package.clj` that is read for dependencies?

Thanks!

**Comment by anmonteiro** [comment] 2017-10-05 17:48
This is a difficult problem with not so good solutions.

My personal favorite way that doesn't suck to work around this is the following:

```clj
#!/bin/sh
"exec" "lumo" "-D" "org.clojure/tools.cli:0.3.5" "$0" "$@"

;; Your code here
```

**Comment by anmonteiro** [comment] 2017-10-05 17:49
I think @SevereOverfl0w has also had some insight on this in the past

**Comment by arichiardi** [comment] 2017-10-05 18:18
Also, is `tools.cli` bootstrap compatible?

**Comment by anmonteiro** [comment] 2017-10-05 18:19
Yes, I've used it before

**Comment by anmonteiro** [comment] 2017-10-05 20:41
Closing as this is not a bug. Let me know if you have further questions.

**Closed by anmonteiro** 2017-10-05 20:41 UTC
Labels: question

**Comment by craigy** [comment] 2017-10-05 22:58
@anmonteiro that shell trick is just what I was looking for, thanks!!
