### ISSUE TITLE
support `lumo --version`

### ISSUE THREAD

**Issue by jab** [anmonteiro/lumo#114] opened 2017-03-29 15:38 UTC
Currently, running `lumo --version` results in `illegal option -- version` getting spewed to the console ad infinitum, which could be a negative experience for new users. Currently version information is output by `lumo -h` (and is also printed when simply running `lumo`), but it could be nice to support the "print version and exit" convention via `--version` (and possibly also -V?). If this is something you'd be interested to add, I'd be happy to try to work up a PR.

Thanks for the great work on lumo and cljs!

**Comment by anmonteiro** [comment] 2017-03-29 15:48
dupe of #112 and #102

**Comment by anmonteiro** [comment] 2017-03-29 15:48
PR welcome for `--version`/`-V` and the infinite loop, though!

**Closed by anmonteiro** 2017-03-29 15:48 UTC
