### ISSUE TITLE
NixOS can't execute Lumo binary

### ISSUE THREAD

**Issue by mfikes** [anmonteiro/lumo#48] opened 2016-11-25 19:42 UTC
```
[vagrant@nixbox:~]$ uname -a
Linux nixbox 4.4.24 #1-NixOS SMP Fri Oct 7 13:23:59 UTC 2016 i686 GNU/Linux

[vagrant@nixbox:~]$ curl -L https://github.com/anmonteiro/lumo/releases/download/1.0.0/lumo_linux64.zip > lumo_linux64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   593    0   593    0     0   4966      0 --:--:-- --:--:-- --:--:--  5294
100 13.1M  100 13.1M    0     0  6754k      0  0:00:01  0:00:01 --:--:-- 8287k

[vagrant@nixbox:~]$ unzip lumo_linux64.zip
Archive:  lumo_linux64.zip
  inflating: lumo

[vagrant@nixbox:~]$ ./lumo
-bash: ./lumo: cannot execute binary file: Exec format error

[vagrant@nixbox:~]$ file lumo
lumo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=9d329f8b37bafc84544ffcc1fbf2f90a25a0a869, not stripped
```

**Comment by anmonteiro** [comment] 2016-11-25 19:43
it seems that you're on a 32-bit machine, trying to run a 64-bit compiled binary.

**Comment by mfikes** [comment] 2016-11-25 20:05
Interestingly, it appears to be actually failing in a really odd way on 64-bit NixOS:

```
[vagrant@nixbox:~]$ uname -a
Linux nixbox 4.4.24 #1-NixOS SMP Fri Oct 7 13:23:59 UTC 2016 x86_64 GNU/Linux

[vagrant@nixbox:~]$ curl -L https://github.com/anmonteiro/lumo/releases/download/1.0.0/lumo_linux64.zip > lumo_linux64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   593    0   593    0     0   5820      0 --:--:-- --:--:-- --:--:--  5871
100 13.1M  100 13.1M    0     0  5824k      0  0:00:02  0:00:02 --:--:-- 6593k

[vagrant@nixbox:~]$ unzip lumo_linux64.zip
Archive:  lumo_linux64.zip
  inflating: lumo

[vagrant@nixbox:~]$ ./lumo
-bash: ./lumo: No such file or directory

[vagrant@nixbox:~]$ file lumo
lumo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=9d329f8b37bafc84544ffcc1fbf2f90a25a0a869, not stripped

[vagrant@nixbox:~]$ ls -l lumo
-rwxr-xr-x 1 vagrant vagrant 45495819 Nov 22 18:06 lumo
```

**Comment by mfikes** [comment] 2016-11-25 20:38
If you look at the "interpreter" part of `file` output for Lumo, you can see that it points at something that is not on this box:

```
[vagrant@nixbox:~]$ file bin/lumo
bin/lumo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=9d329f8b37bafc84544ffcc1fbf2f90a25a0a869, not stripped
```

Here is what is there for Planck (which was built on this box):

```
[vagrant@nixbox:~]$ file planck/planck-c/build/planck
planck/planck-c/build/planck: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

**Comment by mfikes** [comment] 2016-11-25 20:43
Yeah, it is the funky paths that NixOS uses:

```
[vagrant@nixbox:~]$ sudo mkdir /lib64

[vagrant@nixbox:~]$ sudo ln -s /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/ld-linux-x86-64.so.2 /lib64

[vagrant@nixbox:~]$ export LD_LIBRARY_PATH=/nix/store/djd2r4cnbcx4vfbj1qalg85vjbcslwxv-gcc-5.4.0-lib/lib

[vagrant@nixbox:~]$ bin/lumo
Lumo 1.0.0
ClojureScript 1.9.293
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (+ 3 2)
5
```

(I got the `LD_LIBRARY_PATH` setting by looking at Plank's `ldd` output, looking for the path of `libstdc++.so.6`.)

**Comment by mfikes** [comment] 2016-11-25 21:05
You can also workaround it by patching the `lumo` binary:

```
[vagrant@nixbox:~/bin]$ patchelf --set-interpreter /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/ld-linux-x86-64.so.2 lumo

[vagrant@nixbox:~/bin]$ LD_LIBRARY_PATH=/nix/store/djd2r4cnbcx4vfbj1qalg85vjbcslwxv-gcc-5.4.0-lib/lib lumo
Lumo 1.0.0
ClojureScript 1.9.293
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=>
```

**Comment by fstamour** [comment] 2016-11-27 22:40
Got me interested :P
I am able to reproduce
```shell
> nix-shell -p nodejs --run 'npm install lumo-cljs && node_modules/lumo-cljs/bin/lumo'
/
> lumo-cljs@1.0.0 install /home/mpsyco/repo/lumo/node_modules/lumo-cljs
> node scripts/npm_install.js

lumo-cljs@1.0.0 node_modules/lumo-cljs
└── jszip@2.6.1 (pako@1.0.3)
/run/user/1000/nix-shell.u6TKLX/rc: line 1: node_modules/lumo-cljs/bin/lumo: No such file or directory
```
`nix-shell -p nodejs --run 'npm install lumo-cljs && node_modules/lumo-cljs/bin/lumo'` is really cool. It installs the package nodejs in a temporary environment (similar to virtualenv for python), you can guess the rest.

**Comment by fstamour** [comment] 2016-11-27 23:50
I was able to buid it tho.

`build-on-nix.sh :`
```
#!/usr/bin/env bash
set -e

npm install
PATH=$PATH:node_modules/bin/yarn
boot release
```

```
> nix-shell -p boot nodejs-6_x python2 --run ./build-on-nix.sh
>  # ... Really damn looong ...
> build/lumo 
Lumo 1.0.0
ClojureScript 1.9.293
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (+ 1 2)
3
cljs.user=> ⏎ 
```

**Comment by anmonteiro** [comment] 2016-11-28 09:19
So Lumo needs to be built separately if we want it to work in Nix? 
Is there any CI server running Nix so that we can automate that process for every release?

**Comment by fstamour** [comment] 2016-11-28 15:02
P.S. Nix is a package manager (really, it is closer to a full-blown functional language than a simple package manager) and NixOS is a distribution of linux where (almost) _everything_ is manage by nix.

Somebody would have to add a package into the NixOS repository [nixpkgs](https://github.com/NixOS/nixpkgs). Then their build server (named hydra) will rebuild whenever needed (i.e. when the package definition change, for a verion bump for example). So, this issue is related to #9.

Being a _functional_ package manager, one must declare _every_ dependency of lumo in the package (p.s. the build-time dependencies and run-time dependencies are separeated).

One thing that would help a lot the packaging (this is valid for planck too @mfikes) is to separate the scripts that fetches the dependencies from the script that actually build the project.

Here are some related projects that are already packaged: [Clojure](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/interpreters/clojure/default.nix), [Boot](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/tools/build-managers/boot/default.nix), [Lein](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/tools/build-managers/leiningen/default.nix). For planck, I already started to package [linenoise](https://github.com/NixOS/nixpkgs/blob/a4b4495771e421c2537e9e0bc901b086162f6edc/pkgs/development/libraries/linenoise/default.nix) (ATM, it doesn't build anything, it just fetch the sources from github and create a pkg-config file for it). I guess one should package clojurescript by itself so that projects like lumo and planck could depend on it explicitly... but that's yet another story.

Annnd... one last thing. The nix package manager works best on linux (I often hear people using it on archlinux and debian) but I hear that it works on BSDs, MacOS, Plan9... It just won't work on windows, due to a lack of incentive I guess. It is not guaranteed, but packaging something with nix can make it available to a lot of platform.

**Comment by anmonteiro** [comment] 2016-11-28 15:05
That sounds like a lot of work for which I can't spare any time. That said, I'm happy to see Lumo in Nix, so any help is deeply appreciated.

**Comment by fstamour** [comment] 2016-11-28 15:13
I know that would be too much to ask you, I don't have time for this either for the moment. At least there is an issue documenting the situation.

**Comment by anmonteiro** [comment] 2017-04-20 21:18
works with a statically linked binary

```
[vagrant@nixbox:~]$ uname -a
Linux nixbox 4.4.24 #1-NixOS SMP Fri Oct 7 13:23:59 UTC 2016 x86_64 GNU/Linux
[vagrant@nixbox:~]$ ./lumo
Lumo 1.4.0
ClojureScript 1.9.521
Node.js v7.9.0
 Docs: (doc function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=>
```

fixed in #138

**Comment by arichiardi** [comment] 2017-11-16 23:27
I am interested too in a Nix package, can we keep this open until there is one? Searching through closed issues is not ideal :wink:

**Comment by arichiardi** [comment] 2017-11-16 23:30
Sorry, I have pushed the wrong button. On second thought it would be maybe better to open a separate issue.

**Closed by arichiardi** 2017-11-16 23:30 UTC
Labels: help wanted
