### ISSUE TITLE
Shifted command line arguments

### ISSUE THREAD

**Issue by recumbentbirder** [anmonteiro/lumo#343] opened 2018-01-19 14:09 UTC
`(.log js/console js/process.argv)` in a file 'create-users.cljs'

and called with `lumo create-users.cljs -f test.txt`

gives you:

```
[ '/usr/lib/node_modules/lumo-cljs/bin/lumo',
  'nexe.js',
  'create-users.cljs',
  '-f',
  'test.txt' ]
```

Thereby confusing users and libraries, like `command-line-args`, alike, because the expected position of the arguments is shifted by one due to 'nexe.js'. Compiling for nodejs to Javascript results in expected behaviour (because the 'nexe.js' doesn't interfere any longer).

**Comment by arichiardi** [comment] 2018-01-20 01:58
The preferred way is not through `cljs.core/*command-line-args*` and should not present any `nexe` argument.

Which version or lumo are you running? Try `1.8.0-beta` if you are not on it already and please report back.

**Comment by recumbentbirder** [comment] 2018-01-22 14:05
I have 1.8.0-beta.

**Comment by recumbentbirder** [comment] 2018-01-22 14:14
I have 1.8.0-beta.

I put everythin together in one script to see the effect (including \*command-line-args\*):

_test.cljs_:
```
(ns de.clange.test)

(enable-console-print!)

(def command-line-args (js/require "command-line-args"))
(def option-definitions {:name "file" :alias "f" :type js/String})
(def options (command-line-args (clj->js option-definitions)
                                (clj->js {:stopAtFirstUnknown true})))

(println *command-line-args*)
(println options)
```

and _build.cljs_:
```
(require '[lumo.build.api :as b])

(b/build
  (b/inputs "test.cljs")
  {:main 'de.clange.test
   :target :nodejs
   :output-to "out/test.js"})
```

Now, calling the script from lumo via `lumo test.cljs -f test.txt' gives me:

```
(-f test.txt)
#js {:_unknown #js [test.cljs -f test.txt]}
```

Calling the _.js_ after compilation with `lumo build.cljs` with `node out/test.js` gives me:

```
nil
#js {:file test.txt}
```

So obviously, the args are also shifted when using \*command-line-args\*: the parameter 'nexe.js' just seems to be hidden by lumo via a shifting that wreak havoc after compilation to .js.

**Comment by arichiardi** [comment] 2018-01-22 18:07
Closing this one now, I hope the clarification is enough, feel free to reopen it if not.

**Comment by recumbentbirder** [comment] 2018-01-22 20:32
@arichiardi Thanks for your insistence ;-) and I apologize in return for forgetting the 'cljs.core/' ... but the result is the same using `cljs.core/*command-line-args*` in above script: called from lumo, I correctly get `(-f test.txt)`, called via node from the compilation to Javascript I get `nil`. And therefore also different results from a library depending on the command line parameters.

Perhaps I do the build incorrectly?

(Sorry for reopen ;-)

**Comment by arichiardi** [comment] 2018-01-22 20:52
Perhaps it is an actual bug :smile:

**Comment by anmonteiro** [comment] 2018-01-26 17:58
This is not a bug. the fact that `process.argv` has the path to the Lumo binary + `nexe.js` is to maintain compatibility with regular Node.js applications. It's fairly common, if not quite standard behavior, to use `process.argv.slice(2)` to get the actual CLI arguments.

`cljs.core/*command-line-arguments*` respects the behavior of `clojure.main` which adds every argument after a _main option_ to the list.

**Comment by arichiardi** [comment] 2018-01-26 18:02
Agree with the above, we should keep coherence with JS especially with compiled code. From what I understood though, `cljs.core/*command-line-args*` behavior is at discussion here. I haven't tried the snipped above though, so take it with a grain of salt.

**Comment by arichiardi** [comment] 2018-01-28 03:36
So probably the issue is due to some different expectation and some misinformation on my side.
I though `cljs.core*/command-line-args` is effectively only for scripts.

See https://clojure.org/reference/repl_and_main

> To pass in arguments to a script, pass them in as further arguments when launching clojure.main:

For `node`, you have to use host facilities it seems. 

I am leaving this open because it needs documentation (maybe in ClojureScript core?).

**Comment by recumbentbirder** [comment] 2018-01-29 12:14
To me it's still not quite clear, what the matter is. Perhaps it will be clarified in updated docs. I understand Antonio's remark -- my only concern is to have my script behave the same, whether it is called from lumo or as compiled code from node. If possible.
Or would I have to include some checks on which environment it's running in?

**Comment by arichiardi** [comment] 2018-01-29 17:42
I think that if you want to keep the same behavior you'd need to use an `if` because the `cljs.core*/command-line-args` serves another purpose.

I agree it would be desirable to have same behavior, maybe using some other variable?

This issue can evolve from a bug to docs to a feature request :smile:

**Comment by anmonteiro** [comment] 2018-05-13 06:17
@recumbentbirder then use `js/process.argv`, it should be consistent across both lumo and node invocations.

I'm closing this. Please reopen if this still doesn't solve your problem.

**Closed by anmonteiro** 2018-05-13 06:17 UTC
Labels: docs, upstream
