### ISSUE TITLE
Javascript completion only works in readline mode

### ISSUE THREAD

**Issue by arichiardi** [anmonteiro/lumo#103] opened 2017-03-18 02:15 UTC
I read the code and understood this from the code, I am going to look probably into this and improve the completion part if I have time. I might be wrong.

If `lumo` is started with `-d`, which will be the only supported way with `inf-clojure`, then the completion for Javascript classes does not work as I would expect:

    cljs.user=> (lumo.repl/get-completions "(js/con") 
    #js []

In general it would be awesome to complete things like:

    cljs.user=> (def cp (js/require "child_process"))
    #'cljs.user/cp
    cljs.user=> (.ex| cp
    (:exclude  (next                ;; current behavior

     cljs.user=> (cp.|

I know it is very hard to, but we have syntactical advantage with Clojure and we can easily read forms :smile:

**Comment by anmonteiro** [comment] 2017-04-03 20:28
The problem is that we only generate JS completions in the `readline` completer function (see [here](https://github.com/anmonteiro/lumo/blob/8f253f253a618484a5734a74f46814fcfc2f164b/src/js/repl.js#L297-L332))

This probably needs to be merged with the CLJS code

**Closed** 2017-04-11 05:19 UTC
Labels: newbie
